### ISSUE TITLE
Tests are using PloneTestCase, but does not depend on Plone

### ISSUE THREAD

**Issue by jensens** [plone/Products.PlonePAS#10]
All tests are based on bbb PloneTestCase.
But PlonePAS itself has no dependeny on Plone, vice versa is True: Plone depends on PlonePAS.
So test must not pull in Plone. Also this would speed up the test amount of time needed for testing.

**Comment by mauritsvanrees** [comment]
In PlonePAS version 6.0.0 from last year, Philip has ripped out PloneTestCase.
