### ISSUE TITLE
Old-style exception on 5.1 branch

### ISSUE THREAD

**Issue by zopyx** [plone/Products.PlonePAS#44]
https://github.com/plone/Products.PlonePAS/blob/5.x/src/Products/PlonePAS/tools/groupdata.py#L134-L135

Version 5.1.0 is still used in Plone 5.1.X and pinned in the latest 5.1-latest/versions.cfg

**Comment by mauritsvanrees** [comment]
Fixed by yourself in c67891510cbb80a4936936b77db5672e6044a27f.
Closing the issue.
