### ISSUE TITLE
Do we want to support Plone 4 on master?

### ISSUE THREAD

**Issue by jensens** [plone/Products.PlonePAS#8]
We have code supporting Python 2.6 needed for Plone 4, which still runs on 2.6. Needed?

**Comment by gforcada** [comment]
As soon as we have a branch for Plone 4 and master is only Plone 5 most probably can go (if nothing depends on it...)

**Comment by jensens** [comment]
ok, i branch away before my cleanup. i don;t see any reason to have it on 4. also version increase is needed.

**Comment by jensens** [comment]
oh, Plone 4 is already on the 4.1.x branch.

**Comment by jensens** [comment]
after merge this will be solved
